// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Settings struct {
	LibreLinkUpUsername string `json:"LibreLinkUpUsername"`
	LibreLinkUpPassword string `json:"LibreLinkUpPassword"`
	LibreLinkUpRegion   string `json:"LibreLinkUpRegion"`
}
