package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/spagettikod/opent1d/graph/model"
)

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*model.Settings, error) {
	dbsettings, err := r.Store.GetSettings()
	if err != nil {
		return nil, err
	}
	return &model.Settings{
		LibreLinkUpUsername: dbsettings.LibreLinkUpUsername,
		LibreLinkUpRegion:   dbsettings.LibreLinkUpRegion,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
